name: To build Ios

on:
  workflow_call:

jobs:
  build-ios:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Build app for ios
        run: flutter build ios --release --no-codesign
     